### ISSUE TITLE
Issue regarding CUDA version

### ISSUE THREAD

**Issue by ykitanob** [NCGM-genome/WGSpipeline#10]
Dear Support Team,
I am writing to report an issue I encountered when trying to run a Workflow. The ```Tools/*.cwl``` file contains a line that specifies the CUDA version as "cudaVersionMin: 11.4" but when I tried to run the file on my computer, it did not work because my CUDA version is 11.0.

```
[1;30mWARNING[0m  [33mCUDA version '11.0' is less than minimum version '11.4' [0m
[1;30mERROR[0m  [31mWorkflow error:
Could not satisfy CUDARequirement [0m
Traceback (most recent call last):
```
However, I found that changing the line in the ```Tools/*.cwl``` file to "cudaVersionMin: 11.0" allowed me to execute the file correctly.

I am not sure if I should upgrade my CUDA version to 11.4 or if there is another solution to this issue. Could you please provide some guidance on what to do?

**Comment by hacchy1983** [comment]
Hi @ykitanob 
Thank you for your concern. 
I think that changing `cudaVersionMin: 11.4` to `cudaVersionMin: 11.0` might be a solution. 
I will create a new branch within a few days to test this change. 

Best regards, 
Tsuyoshi

**Comment by hacchy1983** [comment]
I changed `cudaVersionMin: 11.4` to `cudaVersionMin: 11.0` in a new branch and tested the execution of tutorials. 
As no error was occurred, the changes were merged into the main branch. 
I would like to close this issue. 
Please feel free to create new issues if you have any problems.

Best,
Tsuyoshi
