### ISSUE TITLE
Question about warnings

### ISSUE THREAD

**Issue by koido** [NCGM-genome/WGSpipeline#9]
In our environment, the following warnings were output from the tutorial:

1.

```
WARNING: underlay of /etc/localtime required more than 50 (80) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (356) bind mounts
```

I guess it's no problem at all.

2.

```
WGSpipeline/Tools/pbrun-fq2cram-multiRGs.cwl:17:3: Warning: checking item
                                                   Warning:   Field `class` contains undefined
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
```

These errors occurred in all tutorials (01 - 03).
I cannot determine the reasons for these warnings.
Do you encounter similar warnings in your environment when running this pipeline?

If necessary, I am more than willing to provide additional information.

Best,
Masaru

**Comment by hacchy1983** [comment]
@koido Thank you for your question. 

```
WARNING: underlay of /etc/localtime required more than 50 (80) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (356) bind mounts
```
Similar warnings were appeared when I executed the tutorials in our environment. 
I also think that these warnings are not a problem. 


```
WGSpipeline/Tools/pbrun-fq2cram-multiRGs.cwl:17:3: Warning: checking item
                                                   Warning:   Field `class` contains undefined
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
WGSpipeline/Tools/pbrun-haplotypecaller-from-cram.cwl:17:3: Warning: checking item
                                                            Warning:   Field `class` contains
```
I think these warning messages may be part of a block of warning messages. 
Could you kindly let me know the following messages?

**Comment by koido** [comment]
Hi @hacchy1983 ,

Thanks for the quick reply.
I attached the shell file and log files for tutorial 03.
Although I masked some parts of directory names, you can check the warnings described above and the following messages.

Many thanks again for your hard work.

Best,
Masaru
[tutorial3_mask.zip](https://github.com/NCGM-genome/WGSpipeline/files/11278991/tutorial3_mask.zip)

**Comment by hacchy1983** [comment]
Hi @koido, 

Thank you for sharing detailed messages. 

```
WGSpipeline/Tools/pbrun-fq2cram-multiRGs.cwl:17:3: Warning: checking item
                                                   Warning:   Field `class` contains undefined
                                                   reference to
                                                   `http://commonwl.org/cwltool#CUDARequirement`
```
Similar warning messages were appeared when I executed the tutorials in our environment. 
I think these warnings are not a problem at all. 

Hi @manabuishii, 
Could you explain the above warnings?
I suspect that the warnings are issues related to the CWL specification and that the warnings are not a problem from a workflow execution point of view.

**Comment by hacchy1983** [comment]
Hi @koido, 

Based on private discussions with @manabuishii and @tom-tan, who are familiar with and/or have contributed to [the common-workflow-language (CWL) project](https://github.com/orgs/common-workflow-language/people), the above warnings may not be a problem, as stderr/stdout messages clearly show that the workflow process has been successfully completed. 

So I would like to close this issue. 
Please feel free to create new issues if you have any problems. 

Best, 
Tsuyoshi
